import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { roboto } from "@/lib/fonts";
import { SideBarLayout } from "@/components/authorized/brand/side-bar/SideBar.component";
import getCurrentUserData from "@/utils/getCurrentUserData";
import { redirect } from "next/navigation";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
	src: "../../fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../../fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const userData = await getCurrentUserData();
	if (!userData) {
		redirect("/login");
	}
	if (userData?.role === "Influencer") {
		redirect("/influencer/oauth");
	}

	return (
		<section
			className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}`}
		>
			<SideBarLayout>{children}</SideBarLayout>
			<Toaster />
		</section>
	);
}
